[versions]
detekt = "1.23.8"
kotlin = "2.3.0"

[libraries]
kris = { module = "ch.difty.kris:kris-core", version = "0.5.25" }
clikt = { module = "com.github.ajalt.clikt:clikt", version = "5.1.0" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.14" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "2.0.17" }
mockk = { module = "io.mockk:mockk", version = "1.14.9" }
kluent = { module = "org.amshove.kluent:kluent", version = "1.73" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version = "6.1.2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

